# -*- coding: utf-8 -*-
"""Inventário de dados do universo Similis Farma (dados, não lógica).

- ``_SUBCATEGORY_INVENTORY``: pares (category_name, subcategory_name) oficiais.
  FONTE: products_categorization (mesmos filtros de subcategory_ids.py). As
  strings devem bater LITERALMENTE com o catálogo. Regenerar rodando a query
  "INVENTÁRIO" de ``sql/discover_metadata_keys.sql`` e colando a coluna
  ``linha_python`` aqui.
- ``ALLOWED_CATEGORY_IDS``: lista fixa de category_ids elegíveis (universo do
  projeto).

A lógica de slug vive em ``parts/slugs.py``; o mapa derivado ``SUBCATEGORIES``
é construído em ``parts/constants.py``.
"""

ALLOWED_CATEGORY_IDS = (
    "441544a1-f917-4584-8ff2-7cfa3b48c026",
    "d1468fe7-2149-47f3-a5b1-52e503c14d49",
    "2830b0a6-515d-448a-adc8-15b2cfecaad2",
    "5ae694e9-fd85-450f-a0fb-ce5782287a47",
    "a7758f5a-f600-4f38-a0b9-71f0d6c37614",
    "2f7c2044-2fb4-48a3-a427-83b602dd34f4",
    "f4c821af-34b5-4903-ab59-886315563e26",
    "7b593e03-6c22-4eaa-8818-f1e05cbfab96",
    "30e61051-75db-4130-b788-37d1d27c7974",
    "07919a47-933f-4960-9d9d-366b898500e5",
    "cdab71f6-5696-4866-89b5-9470b823b27d",
    "30e1ad46-1fe7-4f1b-8be7-5065eef2bab1",
    "394ccd18-0fd5-4695-9373-9d69da99c08b",
    "dce2c931-aafa-40b3-80d9-cfe1e8065eed",
    "a9118230-0005-49da-a05d-306f6d24c7bd",
    "8cbada89-951a-4936-b8af-5c41b26a7e09",
    "77c25f6b-b7c1-4644-9693-7b5512001c73",
    "076cf719-09bc-42e7-a4db-a227907ce0d7",
    "53bd0967-19ba-47ad-8296-924133eda166",
    "b7415aaf-c9a7-4b46-b73a-eebe96426335",
    "a7131086-5340-4818-9471-216cedc8eaee",
    "86a93f75-f0f2-450d-8297-c131d92fcb53",
    "df1bba83-8c31-4be4-9164-a738b8dd6333",
    "94099530-463d-4828-9556-616de7dc4ddf",
    "a1029046-fe88-45bf-a746-c04ddfc76ebb",
    "59a6c9e5-206a-4eea-87fb-041aeb40233a",
    "92b42a2a-3da2-40f0-bdce-c974750ca8d6",
    "de4953f4-33db-435a-8bed-85dbabcbbaac",
    "859aa89c-f23a-4180-824e-e2264bb79754",
    "e7a6e53f-88e4-4720-9fc7-d667eb4c5f84",
    "3700719d-d3f4-4c2d-8205-cc141b624089",
    "ae246074-6aa6-4f7e-b220-a3e075e10fa2",
    "5cb22f87-4a82-4338-ad49-d0827cef6fc8",
    "8caabece-a41c-4b07-8a64-9254688b2fb8",
    "23f18550-5d97-4486-b788-d087bbeb3d6c",
    "7bf5de12-aad4-443d-96f6-0cd221345cb8",
    "adedbcfa-f942-461d-8ed2-6dbe8427b316",
    "30b128fc-da24-427c-a886-e9a4a47ca63c",
    "458cedaf-193c-4051-9396-c2f363a4d6e5",
    "a749a874-c2cc-434b-b4b0-b6e21b72e172",
    "1d3228a7-00d4-4f0f-a188-e9149a202120",
    "78301b09-733d-449f-a270-af457a84d392",
    "f47daf7d-b4f3-449a-9fb1-7403476f0e41",
    "3ed6dc4d-e9c4-4620-bc3a-63af4a793c0e",
    "dc8a1746-cf7e-468c-a814-4c1519b72fba",
    "1463522f-4c8d-4fbd-8a2d-9cfcb3fcb5a0",
    "c61c9531-4f72-471d-8327-b98d4bdc2a93",
    "d0b92f2f-8e4c-4fd7-a371-8bb1190edf12",
    "7c8c45d2-aa27-4145-ac1e-151e0877bde3",
    "581da93d-04c3-45cd-a502-6ab5d9b0fe3a",
    "7ca14e2b-d19a-4433-93d6-0278b34c8534",
    "58b42e2a-7196-4e98-93b7-48b222be5b83",
    "6bdda0ca-20e2-44ab-a6e3-4e6c9b9ba2fd",
    "5cbbac59-b854-45f1-b94c-aef71fcbe7e0",
    "f348dbe9-ca18-4bf6-b8db-1cba96bddd06",
    "5822db7a-0cfe-43d2-a4ff-85cd78916386",
    "95bf85f7-1543-45be-8e8e-70ab92d1d0c4",
    "e8572e51-067a-414f-8802-f80e35a79459",
    "c57b8594-1da8-4109-acbf-36561cfc1a3d",
    "5aa8d5a0-c418-4b3c-96bd-9b3dbc3d6d64",
    "e1cce793-223b-4c30-bc15-a219d6bb0f77",
    "d775b1b0-1e76-45b3-a3f6-44b9b0ff1e0b",
    "7a61364e-8c1b-4cf5-ab7a-d12c0e55cffd",
    "ccc388bd-ff8c-45f0-8dd3-4416b4cacc2f",
    "f074056c-125c-41fe-bc91-aff047fed758",
    "c6b04ae7-fb28-48a7-b0e0-f786a76c910e",
    "2f62f9d6-af2e-4d04-8cc4-99c04625999a",
    "5dec6d7f-6866-4baf-8919-d03a810a011a",
    "8658e25c-3bd4-458b-9999-0b64a8ee69bf",
    "d6f54a61-8409-493d-b3bf-735b4e2b6ab0",
    "b0ec9da0-b04a-4b64-84f4-c5d396cc56c7",
    "3068c2a6-8208-4eed-9d3b-0a95b21199b0",
    "954af7c5-10b9-400a-8641-d0e5b1e1f9c9",
    "d3c9dd43-995c-447b-88d5-d7bdc0d1f9c9",
    "a42f957c-bdf7-4e70-9277-6a3c1153a063",
)


_SUBCATEGORY_INVENTORY = [
    ("Absorvente Diurno", "Absorvente com Abas"),
    ("Absorvente Noturno", "Absorvente com Abas"),
    ("Absorvente Diurno", "Absorvente Interno"),
    ("Absorvente Diurno", "Absorvente sem Abas"),
    ("Absorvente Noturno", "Absorvente sem Abas"),
    ("Amamentação", "Absorventes para Seios"),
    ("Tonalizante e Coloração", "Acessórios para Coloração"),
    ("Maquiagens", "Acessórios para Maquiagem"),
    ("Bebidas", "Achocolatado Pronto"),
    ("Mercado", "Achocolatados e Cia"),
    ("Mercado", "Adoçante"),
    ("Desodorante", "Aerosol"),
    ("Desodorante", "Aerosol e Spray"),
    ("Bebidas", "Água"),
    ("Bebidas", "Água de Coco"),
    ("Antissépticos", "Água Oxigenada e Boricada"),
    ("Bebidas", "Água Tônica"),
    ("Agulhas e Seringas", "Agulhas"),
    ("Prevenção  Viral", "Álcool"),
    ("Mercado", "Alimentos"),
    ("Mercado", "Alimentos Prontos Congelados"),
    ("Mercado", "Alimentos Prontos e Congelados"),
    ("Hidratação e Tratamento Capilar", "Alisantes"),
    ("Shampoo", "Anticaspa e Antiqueda"),
    ("Condicionador", "Anticaspa e Antiqueda"),
    ("Kit Shampoo e Condicionador", "Anticaspa e Antiqueda"),
    ("Antissépticos", "Antissépticos e Tintura Iodo"),
    ("Depilar e Barbear", "Aparelho e Lâmina"),
    ("Aparelhos Elétricos", "Aparelhos Elétricos"),
    ("Casa e Utilidades", "Artigos Esportivos"),
    ("Casa e Utilidades", "Artigos Religiosos"),
    ("Casa e Utilidades", "Automotivos"),
    ("Testes", "Autoteste de Covid"),
    ("Mercado", "Aveias e Cereais"),
    ("Utensílios para Alimentação", "Babadores"),
    ("Aparelhos e Monitores", "Balança"),
    ("Mercado", "Balas e Chicletes"),
    ("Acessórios para Bebês", "Banheira e Acessórios para Banho"),
    ("Mercado", "Barra de Cereal"),
    ("Suplementos", "Barra e Alimentos Proteicos"),
    ("Aparelhos e Monitores", "Baterias para Monitores"),
    ("Suplementos", "BCAA"),
    ("Bebidas", "Bebida Proteica"),
    ("Bebidas", "Bebidas Alcoólicas"),
    ("Bebidas", "Bebidas Vegetais"),
    ("Mercado", "Biscoito de Polvilho"),
    ("Mercado", "Biscoitos e Bolachas Doces"),
    ("Mercado", "Biscoitos e Bolachas Salgadas"),
    ("Algodão", "Bola"),
    ("Ortopédico", "Bolsa Térmica"),
    ("Amamentação", "Bombinha Tira-Leite"),
    ("Ortopédico", "Bota Ortopédica"),
    ("Shampoo", "Branco e Grisalhos"),
    ("Condicionador", "Branco e Grisalhos"),
    ("Kit Shampoo e Condicionador", "Branco e Grisalhos"),
    ("Casa e Utilidades", "Brinquedos"),
    ("Bronzeador", "Bronzeador"),
    ("Banho", "Buchas e Esponjas"),
    ("Dermocosméticos", "Cabelo"),
    ("Condicionador", "Cacheados e Crespos"),
    ("Kit Shampoo e Condicionador", "Cacheados e Crespos"),
    ("Shampoo", "Cacheados e Crespos"),
    ("Condicionador", "Cacheados e Ondulados"),
    ("Hidratação e Tratamento Capilar", "Cacheados e Ondulados"),
    ("Shampoo", "Cacheados e Ondulados"),
    ("Acessórios para Bebês", "Cadeiras e Cadeirão"),
    ("Mercado", "Cafés e Cappuccinos"),
    ("Absorvente Diurno", "Calcinha Absorvente"),
    ("Vitaminas", "Cálcio"),
    ("Casa e Utilidades", "Cama, Mesa e Banho"),
    ("Acessórios para Bebês", "Carrinhos"),
    ("Acessórios para Bebês", "Cercadinho"),
    ("Bebidas", "Cerveja Sem Álcool"),
    ("Mercado", "Cesta de Alimentos"),
    ("Mercado", "Chá"),
    ("Bebidas", "Chá Pronto"),
    ("Kit Shampoo e Condicionador", "Chaceados e Ondulados"),
    ("Casa e Utilidades", "Chip de Celular"),
    ("Acessórios para Bebês", "Chupetas"),
    ("Ortopédico", "Cinta e Meia de Compressão"),
    ("Vitaminas", "Colágeno"),
    ("Absorvente Diurno", "Coletor Menstrual"),
    ("Cuidados com a Pele", "Colônia e Perfumes Infantis"),
    ("Tonalizante e Coloração", "Coloração"),
    ("Tonalizante e Coloração", "Coloração Permanente"),
    ("Tonalizante e Coloração", "Coloração Temporária"),
    ("Casa e Utilidades", "Comemorações e Eventos"),
    ("Cuidados com o Cabelo", "Condicionador Infantil"),
    ("Casa e Utilidades", "Controle de Pragas"),
    ("Utensílios para Alimentação", "Copos e Garrafas"),
    ("Dermocosméticos", "Corpo"),
    ("Proteção Solar", "Corpo"),
    ("Maquiagens", "Corpo"),
    ("Esmalteria", "Cortadores e Lixas"),
    ("Desodorante", "Creme"),
    ("Higiene Oral", "Creme e Gel Dental"),
    ("Higiene Bucal", "Creme e Gel Dental Infantil"),
    ("Troca de Fralda", "Creme para Assaduras"),
    ("Hidratação e Tratamento Capilar", "Creme para Pentear e Leave-in"),
    ("Cuidados com o Cabelo", "Cremes e Gel para Cabelos Infantis"),
    ("Esmalteria", "Cremes para Cutícula"),
    ("Curativos", "Curativos Adesivos"),
    ("Casa e Utilidades", "Decoração"),
    ("Natal", "Decoração e Artigos de Natal"),
    ("Maquiagens", "Demaquilante"),
    ("Depilar e Barbear", "Depilação e Acessórios"),
    ("Dermocosméticos", "Dermocosméticos para Mãos e Pés"),
    ("Dermocosméticos", "Dermocosméticos para o Cabelo"),
    ("Dermocosméticos", "Dermocosméticos para o Corpo"),
    ("Dermocosméticos", "Dermocosméticos para o Rosto"),
    ("Tonalizante e Coloração", "Descoloração"),
    ("Hidratação e Tratamento Capilar", "Desfrizantes"),
    ("Cuidado Íntimo", "Desodorante Íntimo"),
    ("Casa e Utilidades", "Desodorizadores e Aromatizantes"),
    ("Papel Higiênico", "Dispenser"),
    ("Mercado", "Doces e Chocolates"),
    ("Natal", "Doces e Sobremesas de Natal"),
    ("Acessórios para Cabelo", "Elásticos e Presilhas"),
    ("Higiene Bucal", "Enxaguante Bucal Infantil"),
    ("Higiene Oral", "Enxaguante e Antisséptico Bucal"),
    ("Higiene Oral", "Escova Dental"),
    ("Higiene Bucal", "Escova Dental Infantil"),
    ("Loções, Hidratantes e Óleos Corporais", "Esfoliante"),
    ("Esmalteria", "Esmalte e Base"),
    ("Curativos", "Esparadrapos e Micropore"),
    ("Colônia e Perfume", "Feminino"),
    ("Higiene Oral", "Fio e Fita Dental"),
    ("Curativos", "Fitas e Bandagens"),
    ("Higiene Oral", "Fixador de Dentadura"),
    ("Alimentação Infantil", "Fórmula Infantil"),
    ("Cuidado Íntimo", "Fralda Geriátrica"),
    ("Troca de Fralda", "Fraldas"),
    ("Curativos", "Gaze e Ataduras"),
    ("Depilar e Barbear", "Gel e Espuma"),
    ("Gel e Fixador de Cabelo", "Gel e Fixador de Cabelo"),
    ("Desodorante", "Gel e Stick"),
    ("Suplementos", "Glutamina e Creatina"),
    ("Hastes Flexíveis", "Hastes Flexíveis"),
    ("Hidratação e Tratamento Capilar", "Hidratação"),
    ("Hidratação e Tratamento Capilar", "Hidratação e Tratamento Capilar"),
    ("Loções, Hidratantes e Óleos Corporais", "Hidratantes para Mãos e Pés"),
    ("Loções, Hidratantes e Óleos Corporais", "Hidratantes para o Corpo"),
    ("Loções, Hidratantes e Óleos Corporais", "Hidratantes para o Rosto"),
    ("Aparelhos e Monitores", "Inaladores e Umidificadores"),
    ("Colônia e Perfume", "Infantil"),
    ("Bebidas", "Iogurte Diversos"),
    ("Bebidas", "Isotônicos e Energéticos"),
    ("Casa e Utilidades", "Jardinagem"),
    ("Ortopédico", "Joelheira e Tornozeleira"),
    ("Agulhas e Seringas", "Kit"),
    ("Colônia e Perfume", "Kits"),
    ("Maquiagens", "Kits de Maquiagem"),
    ("Banho", "Kits para Viagem"),
    ("Bebidas", "Kombuchas"),
    ("Maquiagens", "Lábios"),
    ("Alimentação Infantil", "Leite em Pó"),
    ("Bebidas", "Leite Fermentado"),
    ("Bebidas", "Leites"),
    ("Cuidado Íntimo", "Lenço Umedecido Íntimo"),
    ("Papel Higiênico", "Lenços"),
    ("Lenços de Papel", "Lenços de Papel"),
    ("Troca de Fralda", "Lenços Umedecidos"),
    ("Casa e Utilidades", "Limpeza de Roupas"),
    ("Shampoo", "Lisos"),
    ("Condicionador", "Lisos"),
    ("Kit Shampoo e Condicionador", "Lisos"),
    ("Shampoo", "Loiros e Coloridos"),
    ("Condicionador", "Loiros e Coloridos"),
    ("Kit Shampoo e Condicionador", "Loiros e Coloridos"),
    ("Saúde Sexual", "Lubrificante"),
    ("Acessórios para Bebês", "Mamadeiras"),
    ("Casa e Utilidades", "Manutenção e Reparo"),
    ("Dermocosméticos", "Mãos e Pés"),
    ("Maquiagens", "Maquiagem para as Sobrancelhas"),
    ("Maquiagens", "Maquiagem para o Corpo"),
    ("Maquiagens", "Maquiagem para o Rosto"),
    ("Maquiagens", "Maquiagem para os Lábios"),
    ("Maquiagens", "Maquiagem para os Olhos"),
    ("Prevenção  Viral", "Máscara"),
    ("Máscaras Faciais", "Máscaras Faciais"),
    ("Colônia e Perfume", "Masculino"),
    ("Ortopédico", "Massageador"),
    ("Hospitalar", "Materiais e Equipamentos"),
    ("Aparelhos e Monitores", "Medidor de Glicose"),
    ("Vitaminas", "Minerais"),
    ("Acessórios de Beleza", "Modelador de Seio e Adesivos"),
    ("Aparelhos e Monitores", "Monitor de Pressão"),
    ("Acessórios para Bebês", "Mordedores"),
    ("Acessórios para Bebês", "Mordedores e Chocalhos"),
    ("Ortopédico", "Muleta e Bengala"),
    ("Vitaminas", "Multivitamínicos"),
    ("Casa e Utilidades", "Mundo Pet"),
    ("Ortopédico", "Munhequeira e Cotoveleira"),
    ("Desodorante", "Natural e Vegano"),
    ("Suplementos", "Nutricosméticos"),
    ("Loções, Hidratantes e Óleos Corporais", "Óleo Corporal"),
    ("Hidratação e Tratamento Capilar", "Óleos e Finalizadores"),
    ("Cuidados com a Pele", "Óleos e Hidratantes Infantis"),
    ("Shampoo", "Oleosos e Misto"),
    ("Condicionador", "Oleosos e Misto"),
    ("Hidratação e Tratamento Capilar", "Oleosos e Misto"),
    ("Kit Shampoo e Condicionador", "Oleosos e Misto"),
    ("Maquiagens", "Olhos"),
    ("Vitaminas", "Ômega3"),
    ("Bebidas", "Outras Bebidas"),
    ("Testes", "Outros"),
    ("Aparelhos e Monitores", "Outros"),
    ("Casa e Utilidades", "Outros"),
    ("Mercado", "Outros"),
    ("Outros", "Outros"),
    ("Hidratação e Tratamento Capilar", "Outros"),
    ("Acessórios para Cabelo", "Outros"),
    ("Esmalteria", "Outros"),
    ("Higiene Oral", "Outros"),
    ("Banho", "Outros"),
    ("Acessórios de Beleza", "Outros"),
    ("Depilar e Barbear", "Outros"),
    ("Cuidado Íntimo", "Outros"),
    ("Cuidados com o Cabelo", "Outros"),
    ("Alimentação Infantil", "Outros"),
    ("Amamentação", "Outros"),
    ("Cuidados com a Pele", "Outros"),
    ("Ortopédico", "Outros"),
    ("Saúde Sexual", "Outros"),
    ("Hospitalar", "Outros"),
    ("Suplementos", "Outros"),
    ("Vitaminas", "Outros"),
    ("Acessórios para Bebês", "Outros Acessórios"),
    ("Acessórios para Cabelo", "Outros Acessórios para Cabelo"),
    ("Dermocosméticos", "Outros Dermocosméticos"),
    ("Utensílios para Alimentação", "Outros Utensílios"),
    ("Aparelhos e Monitores", "Oxímetros"),
    ("Natal", "Panetones e Chocotones"),
    ("Casa e Utilidades", "Papelaria e Livros"),
    ("Alimentação Infantil", "Papinha"),
    ("Acessórios para Cabelo", "Para Corte"),
    ("Loções, Hidratantes e Óleos Corporais", "Para Massagem"),
    ("Desodorante", "Para os Pés"),
    ("Higiene Oral", "Passador de Fio"),
    ("Acessórios para Cabelo", "Pentes e Escovas"),
    ("Protetor Solar", "Pós Sol"),
    ("Proteção Solar", "Pós Sol"),
    ("Depilar e Barbear", "Pós-Barba"),
    ("Casa e Utilidades", "Praia e Piscina"),
    ("Suplementos", "Pré-treinos"),
    ("Saúde Sexual", "Preservativo"),
    ("Casa e Utilidades", "Produtos para Limpeza"),
    ("Suplementos", "Proteínas"),
    ("Absorvente Diurno", "Protetor Diário"),
    ("Amamentação", "Protetor e Pomada para Seios"),
    ("Cuidados com a Pele", "Protetor Solar Infantil"),
    ("Proteção Solar", "Protetor Solar para o Corpo"),
    ("Proteção Solar", "Protetor Solar para o Rosto"),
    ("Algodão", "Quadrado e Disco"),
    ("Condicionador", "Quimicamente Tratados"),
    ("Shampoo", "Quimicamente Tratados"),
    ("Kit Shampoo e Condicionador", "Quimicamente Tratados"),
    ("Hidratação e Tratamento Capilar", "Quimicamente Tratados"),
    ("Amamentação", "Recipiente para Leite Materno"),
    ("Bebidas", "Refrigerantes"),
    ("Esmalteria", "Removedor de Esmalte"),
    ("Cuidados com a Pele", "Repelente Infantil"),
    ("Repelentes", "Repelentes"),
    ("Casa e Utilidades", "Repelentes e Controle de Pragas"),
    ("Shampoo", "Ressecados e Secos"),
    ("Kit Shampoo e Condicionador", "Ressecados e Secos"),
    ("Condicionador", "Ressecados e Secos"),
    ("Hidratação e Tratamento Capilar", "Ressecados e Secos"),
    ("Desodorante", "Roll-on"),
    ("Algodão", "Rolo"),
    ("Papel Higiênico", "Rolos"),
    ("Dermocosméticos", "Rosto"),
    ("Proteção Solar", "Rosto"),
    ("Maquiagens", "Rosto"),
    ("Cuidado Íntimo", "Roupa Íntima Descartável"),
    ("Casa e Utilidades", "Roupas e Calçados"),
    ("Hospitalar", "Roupas e Calçados"),
    ("Cuidados com a Pele", "Sabonete Infantil"),
    ("Cuidado Íntimo", "Sabonete Íntimo"),
    ("Banho", "Sabonetes"),
    ("Mercado", "Salgadinho"),
    ("Agulhas e Seringas", "Seringas"),
    ("Depilar e Barbear", "Shampoo e Modeladores de Barba"),
    ("Cuidados com o Cabelo", "Shampoo Infantil"),
    ("Mercado", "Snacks"),
    ("Loções, Hidratantes e Óleos Corporais", "Solução Micelar"),
    ("Higienização", "Soro Fisiológico"),
    ("Mercado", "Sorvete"),
    ("Mercado", "Sorvetes e Açaís"),
    ("Bebidas", "Sucos"),
    ("Troca de Fralda", "Talco"),
    ("Utensílios para Alimentação", "Talheres e Pratinhos"),
    ("Aparelhos e Monitores", "Termômetros"),
    ("Testes", "Teste Gravidez e Fertilidade"),
    ("Testes", "Teste HIV"),
    ("Testes", "Teste Mapeamento Genético"),
    ("Ortopédico", "Tipóia e Colar Cervical"),
    ("Shampoo", "Todos os Tipos"),
    ("Condicionador", "Todos os Tipos"),
    ("Kit Shampoo e Condicionador", "Todos os Tipos"),
    ("Hidratação e Tratamento Capilar", "Todos os Tipos"),
    ("Tonalizante e Coloração", "Tonalizante"),
    ("Hidratação e Tratamento Capilar", "Tônico"),
    ("Banho", "Toucas"),
    ("Esmalteria", "Unhas Postiças"),
    ("Colônia e Perfume", "Unissex"),
    ("Casa e Utilidades", "Utensílios para Cozinha"),
    ("Casa e Utilidades", "Utilidades Diversos"),
    ("Antissépticos", "Vaselina"),
    ("Saúde Sexual", "Vibrador e Estimulador"),
    ("Vitaminas", "Vitamina Bs"),
    ("Vitaminas", "Vitamina C"),
    ("Vitaminas", "Vitamina D"),
    ("Vitaminas", "Vitamina E"),
]
